name: AtCoder Submissions Crawler (all)

on:
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl AtCoder Submissions
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 100
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r _src/requirements.txt
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Crawl and Commit
        run: python _src/main.py fetch_all
      - name: Push
        run: git push
